### ISSUE TITLE
dbt outputs are not captured when using other task runners than Docker or Process

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dbt#113]
You can see that when using KubernetesTaskRunner the outputs are not captured and therefore the `run_results.json` is also not parsed:

![image](https://github.com/kestra-io/plugin-dbt/assets/86264395/b9a67b34-896f-4086-a3c3-b3fc0403dd45)

(no models rendered)

![image](https://github.com/kestra-io/plugin-dbt/assets/86264395/4c69fb83-9046-4866-a06d-03f870f5e2c8)

When you instead use DockerTaskRunner, you can see properly captured outputs and models:

![image](https://github.com/kestra-io/plugin-dbt/assets/86264395/0ced2136-68b0-4251-af70-7e838d77a03c)

![image](https://github.com/kestra-io/plugin-dbt/assets/86264395/9d7b7ccf-382f-495f-bfbf-f7a32935e8f9)

Reproducer:

```yaml
id: dbt_kubernetes
namespace: dwh
description: Download https://github.com/kestra-io/dbt-example as a zipfile and import to the Namespace Files editor. 
tasks:
  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    namespaceFiles:
      enabled: true
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    commands:
      - dbt build --profiles-dir {{workingDir}}/dbt/ --project-dir {{workingDir}}/dbt/

taskDefaults:
  - type: io.kestra.plugin.dbt.cli
    values:
      taskRunner:
        type: io.kestra.plugin.kubernetes.runner.KubernetesTaskRunner
        config:
          # masterUrl: https://docker-for-desktop:6443 # when running kestra in docker
          masterUrl: https://127.0.0.1:6443
          clientKey: xxx==
          clientCert: xxx==
          caCert: xxx
          username: docker-desktop
          namespace: default
```
