### ISSUE TITLE
dbt CLI doesn't render results when specifying a custom target from CLI

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dbt#127]
The `target` provided via CLI arguments needs to take precedence over the `target` specified in the `profiles` property or `profiles.yml` file. Currently, that works for execution, but when overwriting the target from CLI, the dbt DAG is not parsed at runtime.

Reproducer:

```yaml
id: dwh_and_analytics
namespace: company.team
description: |
  ## Data Platform
  Clone a [Git repository](https://github.com/kestra-io/dbt-example) and build dbt models

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: clone_repository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-example
      branch: master

    - id: dbt_build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
      commands:
        - dbt deps --project-dir dbt --target prod
        - dbt build --project-dir dbt --target prod
      profiles: |
        my_dbt_project:
          outputs:
            dev:
              type: duckdb
              path: dbt.duckdb
              extensions: 
                - parquet
              fixed_retries: 1
              threads: 16
              timeout_seconds: 300
            prod:
              type: duckdb
              path: dbt2.duckdb
              extensions: 
                - parquet
              fixed_retries: 1
              threads: 16
              timeout_seconds: 300
          target: dev
```

no dbt models/tests are parsed when overwriting the target via CLI 
![image](https://github.com/kestra-io/plugin-dbt/assets/86264395/0e66a4c5-92df-4c82-9288-131ffaef35b5)
