### ISSUE TITLE
dbt CLI task fails immediately if `profiles` is not provided as task property but rather existing in the current wdir

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dbt#146]
### Issue description

Error:

```
Cannot invoke "[io.kestra.core.models.property.Property.as](http://io.kestra.core.models.property.property.as/)(io.kestra.core.runners.RunContext, java.lang.Class)" because "this.profiles" is null
2024-10-03 23:36:58.892java.lang.NullPointerException: Cannot invoke "io.kestra.core.models.property.Property.as(io.kestra.core.runners.RunContext, java.lang.Class)" because "this.profiles" is null at io.kestra.plugin.dbt.cli.DbtCLI.run(DbtCLI.java:253) at io.kestra.plugin.dbt.cli.DbtCLI.run(DbtCLI.java:39) at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:77) at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)
```

To reproduce, run dbt with profiles.yaml being in the root directory and not specified in the task:

```yaml
id: dbt_build
namespace: company.team

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/dbt-example
        branch: main

      - id: dbt-build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        commands:
          - dbt build
```

You can also clone that above repo, upload as namespace files and add file profiles.yaml in the root dir:

```yaml
my_dbt_project:
  outputs:
    dev:
      type: duckdb
      path: ":memory:"
  target: dev
```

**Comment by brian-mulier-p** [comment]
closed by https://github.com/kestra-io/plugin-dbt/commit/efbeb56a18ad0f0dc575ab886f1b4a0e71df9b24

**Comment by anna-geller** [comment]
maybe it's a build issue, in that case you can close after validating the fix is on develop

for now on develop I still see the issue:

```Java
java.lang.NullPointerException: Cannot invoke "[io.kestra.core.models.property.Property.as](http://io.kestra.core.models.property.property.as/)(io.kestra.core.runners.RunContext, java.lang.Class)" because "this.profiles" is null at io.kestra.plugin.dbt.cli.DbtCLI.run(DbtCLI.java:253) at io.kestra.plugin.dbt.cli.DbtCLI.run(DbtCLI.java:39) at io.kestra.core.runners.WorkerTaskCallable.doCall(WorkerTaskCallable.java:78) at io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:56) at io.kestra.core.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10) at io.kestra.core.runners.Worker.callJob(Worker.java:783) at io.kestra.core.runners.Worker.runAttempt(Worker.java:742) at io.kestra.core.runners.Worker.run(Worker.java:599) at io.kestra.core.runners.Worker.handleTask(Worker.java:284) at io.kestra.core.runners.Worker.lambda$run$7(Worker.java:240) at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
```

Reproducer:
```yaml
id: dbt_build
namespace: company.team

tasks:
  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    disabled: true
    url: https://github.com/kestra-io/dbt-example
    branch: master
    namespace: company.team
    gitDirectory: dbt
    dryRun: false

  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    commands:
      - dbt build
```

**Comment by brian-mulier-p** [comment]
As said it wasn't built yet. After build it's working properly
![Uploading image.png…]()

**Comment by anna-geller** [comment]
confirmed, it's working now, thx Brian 👍 

```yaml
id: dbt_build
namespace: company.team

tasks:
  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/kestra-io/dbt-example
    branch: master
    namespace: company.team
    gitDirectory: dbt
    dryRun: false

  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    commands:
      - dbt build
```
