### ISSUE TITLE
Instead of overwriting the profile, providing dbt profiles via dbt task property gives `java.nio.file.FileAlreadyExistsException`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dbt#147]
### Feature description

reproducer:
```yaml
id: dbt_build
namespace: company.team
description: |
  to reproduce, download /tree/master

  unzip and "Import folder" - to import dbt folder and upload the contents of the dbt directory as namespace files
tasks:
  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/kestra-io/dbt-example
    branch: master
    namespace: company.team
    gitDirectory: dbt
    dryRun: false

  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    commands:
      - dbt build
    profiles: |
      my_dbt_project:
        outputs:
          dev:
            type: duckdb
            path: ":memory:"
        target: dev    
```

error:

```
java.nio.file.FileAlreadyExistsException: /tmp/3a36oa9laKOXOGbZhCdw4R/profiles.yml at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) at java.base/java.nio.file.Files.newByteChannel(Unknown Source) at java.base/java.nio.file.Files.createFile(Unknown Source) at io.kestra.core.runners.LocalWorkingDir.createFile(LocalWorkingDir.java:163) at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.lambda$run$0(CommandsWrapper.java:143) at io.kestra.core.utils.Rethrow.lambda$throwConsumer$0(Rethrow.java:50) at java.base/java.lang.Iterable.forEach(Unknown Source) at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:141) at io.kestra.plugin.dbt.cli.DbtCLI.run(DbtCLI.java:284) at io.kestra.plugin.dbt.cli.DbtCLI.run(DbtCLI.java:39) at io.kestra.core.runners.WorkerTaskCallable.doCall(WorkerTaskCallable.java:78) at io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:56) at io.kestra.core.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10) at io.kestra.core.runners.Worker.callJob(Worker.java:783) at io.kestra.core.runners.Worker.runAttempt(Worker.java:742) at io.kestra.core.runners.Worker.run(Worker.java:599) at io.kestra.core.runners.Worker.handleTask(Worker.java:284) at io.kestra.core.runners.Worker.lambda$run$7(Worker.java:240) at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
```
