### ISSUE TITLE
Regression in dbt-plugin and kestra 0.19.x: UnsupportedOperationException

### ISSUE THREAD

**Issue by lburja** [kestra-io/plugin-dbt#148]
### Describe the issue

When upgrading from v0.18.9 to v0.19.1, all dbt tasks fail with this stacktrace:

```
2024-10-07 09:38:50.720

java.lang.UnsupportedOperationException
 at java.base/java.util.AbstractMap.put(Unknown Source)
 at java.base/java.util.AbstractMap.putAll(Unknown Source)
 at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.addEnv(CommandsWrapper.java:129)
 at io.kestra.plugin.dbt.cli.AbstractDbt.run(AbstractDbt.java:183)
 at io.kestra.plugin.dbt.cli.AbstractDbt.run(AbstractDbt.java:35)
 at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:76)
 at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)
```

Switching back fixes the issue.
Not sure how to reproduce it on your side, but the root cause is obvious.

In `AbstractDbt:183`, the plugin tries to add some environment variables:
![image](https://github.com/user-attachments/assets/4e207d1a-a8e5-46a3-89a9-2a6248c144ca)

But a few lines above, you can see that in certain conditions, the `env` property is initialized to `Collections.emptyMap()`, which is immutable (hence the error):
![image](https://github.com/user-attachments/assets/4ac60da5-1afd-458a-bf18-ab337a834992)

### Environment

- Kestra Version: v0.19.1
- Operating System (OS/Docker/Kubernetes): Kubernetes
- Java Version (if you don't run kestra in Docker):

**Comment by Ben8t** [comment]
@lburja I'm not able to reproduce on 0.19.1 - can you details what's your Kestra configuration/installation please ?

**Comment by lburja** [comment]
Sure, here is a minimal example that reproduces the issue in my setup:

```
id: dbt-bug
namespace: playground

pluginDefaults:
  - type: io.kestra.plugin.dbt.cli
    values:
      containerImage: registry.cis.consilium.europa.eu/dpl/kestra-python:3.12.35
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
        credentials:
          username: "{{ envs.harbor_username }}"
          password: "{{ secret('HARBOR_PASSWORD') }}"

tasks:
  - id: dbt
    type: io.kestra.plugin.dbt.cli.Build
```

Result:

![image](https://github.com/user-attachments/assets/894f90f3-984d-403e-b440-e8f1719e5a07)

Please note:
- to reproduce it on your side, you'll need to specify other plugin defaults (use your own container image, your own credentials, etc.)

**Comment by Ben8t** [comment]
Unfortunelty I still can't reproduce:

```yaml
id: dbt_build
namespace: company.team.dbt

tasks:
  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/kestra-io/dbt-example
    branch: master
    namespace: company.team.dbt
    gitDirectory: dbt
    dryRun: false

  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    commands:
      - dbt build

pluginDefaults:
  - type: io.kestra.plugin.dbt.cli
    values:
      containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
```

Can you try this one on your side please ?

**Comment by lburja** [comment]
The issue does not exist with DbtCLI. That one works fine for me as well.

I only have issues when I use io.kestra.plugin.dbt.cli.Build (also
io.kestra.plugin.dbt.cli.List and any other task except DbtCLI which for
some reason works fine)

**Comment by Ben8t** [comment]
Thanks for the precision, I'm able to reproduce:

```yaml
id: dbt_build
namespace: company.team.dbt

tasks:
  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/kestra-io/dbt-example
    branch: master
    namespace: company.team.dbt
    gitDirectory: dbt
    dryRun: false

  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.Build
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    namespaceFiles:
      enabled: true
```

cc @mgabelle, as @lburja pointed out the error is probably around that `AbstractDbt:183`
