### ISSUE TITLE
Unable to use DBT-CLI using the default postgres dbt image

### ISSUE THREAD

**Issue by bbouretdev** [kestra-io/plugin-dbt#149]
### Expected Behavior

Using "ghcr.io/kestra-io/dbt-postgres:latest" container image inside a DBT-CLI task (io.kestra.plugin.dbt.cli.DbtCLI) should install a working postgres adapter version, enabling DBT commands to run properly.

### Actual Behaviour

This stacktrace appears on flow execution: "Error importing adapter: No module named 'dbt.adapters.postgres'".

It seems to work when using "beforeCommands: pip install dbt-postgres" instead of "containerImage" as a workaround

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
it was updated 4 days ago, so everything works on CI side https://github.com/kestra-io/plugin-dbt/actions/runs/11212170143

@Ben8t can you try to reproduce on the same postgres you run kestra on with docker compose?

**Comment by Ben8t** [comment]
Indeed last builds shoudl have fixed
I'm able to run dbt.CLI with Postgres containerImage successfully:

```yaml
id: transform
namespace: kestra.weather

concurrency:
  behavior: QUEUE
  limit: 1

tasks:
  - id: git
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Ben8t/dbt_weather.git
        branch: main

      - id: dbt
        type: io.kestra.plugin.dbt.cli.DbtCLI
        containerImage: ghcr.io/kestra-io/dbt-postgres:latest
        profiles: |
          dbt_weather:
            outputs:
              dev:
                type: postgres
                host: "{{ secret('POSTGRES_HOST') }}"
                user: "{{ secret('POSTGRES_USERNAME') }}"
                password: "{{ secret('POSTGRES_PASSWORD') }}"
                port: 5432
                dbname: data
                schema: weather
                threads: 8
                connect_timeout: 10
            target: dev
        commands:
          - dbt deps
          - dbt build
      
triggers:
  - id: listen-flow
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionFlowCondition
        namespace: kestra.weather
        flowId: load
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - SUCCESS
```

![image](https://github.com/user-attachments/assets/d9a3566b-cd88-4a50-96ba-30d23dbfb00e)


Closing for now. @bbouretdev do not hesitate to give a full reproducer if you still face an issue here
