### ISSUE TITLE
The loadManifest property seems to have no effect as manifest.json is not injected into the working directory

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dbt#156]
### Issue description

This warning is logged when using the default example:

> Unable to do partial parsing because saved manifest not found. Starting full parse.

```yaml
id: dbt_duckdb
namespace: company.team
tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/dbt-example
        branch: main

      - id: dbt_build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          delete: true
        containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
        loadManifest:
          key: manifest.json
          namespace: company.team
        storeManifest:
          key: manifest.json
          namespace: company.team
        commands:
          - dbt build --defer --state ./target --target prod

        profiles: |
          my_dbt_project:
            outputs:
              dev:
                type: duckdb
                path: ":memory:"
                fixed_retries: 1
                threads: 16
                timeout_seconds: 300
              prod:
                type: duckdb
                path: dbt2.duckdb
                extensions:
                  - parquet
                fixed_retries: 1
                threads: 16
                timeout_seconds: 300
            target: dev
```

**Comment by anna-geller** [comment]
the example in the plugin docs was confusing. adding select will make it work:

```yaml
id: dbt_build
namespace: company.datateam.dbt

tasks:
  - id: dbt
    type: io.kestra.plugin.dbt.cli.DbtCLI
    namespaceFiles:
      enabled: true
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    projectDir: dbt
    commands:
      - dbt build --select state:modified+ --project-dir dbt --profiles-dir dbt --defer --state ./target --target prod --no-partial-parse
    loadManifest:
      key: manifest.json
      namespace: "{{ flow.namespace }}"
    storeManifest:
      key: manifest.json
      namespace: "{{ flow.namespace }}"     
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
```

will correct the docs and close the issue
