### ISSUE TITLE
'pluginDefaults' is ignored for dbt commands 

### ISSUE THREAD

**Issue by lburja** [kestra-io/plugin-dbt#158]
### Describe the issue

In dbt-plugin version `0.20.0-SNAPSHOT` (which fixes #148), when using any dbt command, such as `io.kestra.plugin.dbt.cli.List`, the values in `pluginDefaults` are ignored.

For example:

```
id: dbt-bug-pluginDefaults
namespace: company.team

pluginDefaults:
  - type: io.kestra.plugin.dbt.cli
    values:        
      dbtPath: /usr/local/bin/dbt
      containerImage: registry.cis.consilium.europa.eu/dpl/kestra-python:3.12.35

tasks:
  - id: create_dummy_dbt_project
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: shell
      type: io.kestra.plugin.scripts.shell.Commands
      commands:
        - |
          echo "name: my_project \nversion: '1.0' \nprofile: default \nmodel-paths: ['models'] \ntarget-path: 'target' \nclean-targets: ['target']" > {{ workingDir }}/dbt_project.yml

    - id: dbt
      type: io.kestra.plugin.dbt.cli.List
      projectDir: /
      profiles: |
        default:
          outputs:
            dev:
              type: duckdb
              threads: 1
          target: dev
```

This should pull the image `registry.cis.consilium.europa.eu/dpl/kestra-python:3.12.35`, but instead I see in the logs that it tries to pull the default `ghcr.io/kestra-io/dbt`.

This is true for any property, e.g. `dbtPath` is also ignored.

## How to reproduce

Use the flow above, and notice that the values in `pluginDefaults` are ignored. Remember to use dbt-plugin version 0.20.0-SNAPSHOT or above (otherwise you'll hit #148 first).

### Environment

- Kestra Version: 0.19.x
- dbt-plugin version: 0.20.0-SNAPSHOT

**Comment by Ben8t** [comment]
Hello @lburja,
I'm not able to reproduce anymore on `kestra:develop`. 

```yaml
id: dbt_build
namespace: mgabelle.test.dbt

pluginDefaults:
  - type: io.kestra.plugin.dbt.cli
    values:        
      containerImage: ghcr.io/kestra-io/dbt-duckdb
      dbtPath: /usr/local/bin/dbt

tasks:
  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/kestra-io/dbt-example
    branch: master
    namespace: mgabelle.test.dbt
    gitDirectory: dbt
    dryRun: false

  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.List
    profiles: |
      my_dbt_project:
        outputs:
          dev:
            type: duckdb
            path: ':memory:'
            extensions:
              - parquet
        target: dev
    namespaceFiles:
      enabled: true
```

I'm closing for now, do not hesitate to share more information/reproducer if you still encounter the issue.
