### ISSUE TITLE
A dbt task state warning doesn't change the flow state to warning

### ISSUE THREAD

**Issue by gabriel-kasmi-corail** [kestra-io/plugin-dbt#189]
### Describe the issue

I have a flow with a dbt build task (which involves multiple tables)
The logs indicate `33 WARNINGS`, but the total state of the flow is indicated as `SUCCESS`
on your documentation, it says
> WARNING: This terminal state is used when the execution has completed successfully, but one or more tasks have emitted warnings.

![Image](https://github.com/user-attachments/assets/773591b3-70e1-496d-9afe-c140c2456ba1)

![Image](https://github.com/user-attachments/assets/d208c78c-78e7-4d7e-8432-da348fb46576)

### Environment

- Kestra Version: v0.22.1 (self-hosted)

**Comment by Ben8t** [comment]
Here is a reproducer:

```yaml
id: dbt-duckdb
namespace: company.team

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/dbt-example
        branch: main

      - id: dbt_build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
        namespaceFiles:
          enabled: true
        commands:
          - dbt deps
          - dbt build
          - dbt run-operation emit_warning_log
        profiles: |
          my_dbt_project:
            outputs:
              dev:
                type: duckdb
                path: ":memory:"
                fixed_retries: 1
                threads: 16
                timeout_seconds: 300
            target: dev
```

You should create the following macro in a `macros/my_sql.sql` namespacesFiles

```sql
{% macro emit_warning_log() %}
    {% do exceptions.warn("This is a warning from dbt") %}
{% endmacro %}
```

![Image](https://github.com/user-attachments/assets/71f23382-419b-4f97-be16-48e352fcca01)

**Comment by anna-geller** [comment]
took a while but found a reliable reproducer -- the previous one doesn't generate warnings in dbt build, this one will help you reproduce @Malaydewangan09 

```yaml
id: dbt_warn
namespace: company.team

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/dbt-demo
        branch: warn

      - id: dbt_build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
        commands:
          - dbt deps
          - dbt build
```

![Image](https://github.com/user-attachments/assets/f3bdd94a-30f3-4c27-ad67-50e0ca314833)

the issue is not tied to 0.22 or 0.23 but apparently even older
