### ISSUE TITLE
Unknown type error triggering job run on dbt cloud

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-dbt#191]
### Describe the issue

Running a simple job in dbt cloud, although the job succeeds on their platform results in an error in Kestra

```
id: dbt_cloud
namespace: solutions.demo

tasks:
  - id: trigger_job
    type: io.kestra.plugin.dbt.cloud.TriggerRun
    jobId: "1234"
    accountId: "5678"
    token: "{{secret('dbt-token')}}"
    cause: "this is the message"
    wait: true
```

error:
```
2025-05-19 21:18:04.997Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
```

### Environment

- Kestra Version: 0.22.4
