### ISSUE TITLE
`dbt.cli.Deps` task returns an error `java.io.FileNotFoundException: /tmp/kestra-wd/tmp/xxx/target/run_results.json`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dbt#37]
### Expected Behavior

reproducer:

```yaml
id: dbtGitDockerBigQuery
namespace: dev

tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/dbt-labs/jaffle_shop
      branch: main

    - id: dbt-deps
      type: io.kestra.plugin.dbt.cli.Deps
      runner: DOCKER
      dbtPath: /usr/local/bin/dbt
      dockerOptions:
        image: ghcr.io/kestra-io/dbt-bigquery:latest
      inputFiles:
        .profile/profiles.yml: |
          jaffle_shop:
            outputs:
              dev:
                type: bigquery
                dataset: dwh
                fixed_retries: 1
                keyfile: sa.json
                location: EU
                method: service-account
                priority: interactive
                project: geller
                threads: 8
                timeout_seconds: 300
            target: dev
        sa.json: "{{ secret('GCP_CREDS') }}"

    - id: dbt-build
      type: io.kestra.plugin.dbt.cli.Build
      runner: DOCKER
      dbtPath: /usr/local/bin/dbt
      dockerOptions:
        image: ghcr.io/kestra-io/dbt-bigquery:latest
      inputFiles:
        .profile/profiles.yml: |
          jaffle_shop:
            outputs:
              dev:
                type: bigquery
                dataset: dwh
                fixed_retries: 1
                keyfile: sa.json
                location: EU
                method: service-account
                priority: interactive
                project: geller
                threads: 8
                timeout_seconds: 300
            target: dev
        sa.json: "{{ secret('GCP_CREDS') }}"
```

### Actual Behaviour

![image](https://github.com/kestra-io/plugin-dbt/assets/86264395/2ec21410-c98f-4fda-9820-8eee75ce4006)

full traceback:

```
dbt-deps
23s
Image pulled [ghcr.io/kestra-io/dbt-bigquery:latest]
Starting command with container id 161caeb3e1981f891f246decfe27861841c2e4cda383384adc9a33c1c8094c01 [/bin/sh -c /usr/local/bin/dbt --log-format json deps --profiles-dir /tmp/kestra-wd/tmp/3JmZq0jWaAuOBtMmcYWcMP/.profile]
[Date: 2023-07-17T23:11:20.477322Z] [Thread: MainThread] [Type: MainReportVersion] Running with dbt=1.5.2 
[Date: 2023-07-17T23:11:20.691006Z] [Thread: MainThread] [Type: DepsNoPackagesFound] Warning: No packages were found in packages.yml 
Command succeed with code 0
/tmp/kestra-wd/tmp/3JmZq0jWaAuOBtMmcYWcMP/target/run_results.json (No such file or directory)
java.io.FileNotFoundException: /tmp/kestra-wd/tmp/3JmZq0jWaAuOBtMmcYWcMP/target/run_results.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at com.fasterxml.jackson.core.TokenStreamFactory._fileInputStream(TokenStreamFactory.java:262)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1030)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3542)
	at io.kestra.plugin.dbt.ResultParser.parseRunResult(ResultParser.java:38)
	at io.kestra.plugin.dbt.cli.AbstractDbt.run(AbstractDbt.java:100)
	at io.kestra.plugin.dbt.cli.AbstractDbt.run(AbstractDbt.java:20)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:641)
```

### Environment Information

- Kestra Version: 0.10.1 develop full

**Comment by anna-geller** [comment]
alternative solution as a workaround:

```yaml
id: dbtCLI
namespace: dev

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/dbt-labs/jaffle_shop
        branch: main

      - id: profile
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          profiles.yml: |
            jaffle_shop:
              outputs:
                dev:
                  type: bigquery
                  dataset: dwh
                  fixed_retries: 1
                  keyfile: sa.json
                  location: EU
                  method: service-account
                  priority: interactive
                  project: geller
                  threads: 8
                  timeout_seconds: 300
              target: dev
          sa.json: "{{ secret('GCP_CREDS') }}"

      - id: dbt
        type: io.kestra.plugin.scripts.shell.Commands
        docker:
          image: ghcr.io/kestra-io/dbt-bigquery:latest
        commands:
          - dbt deps --profiles-dir .
          - dbt build --profiles-dir .
```

this doesn't compile a Gantt view for built models and tests though

**Comment by loicmathieu** [comment]
@anna-geller thee `dbt deps` is useless here as there is no `packages.yml` files here so no package to install.
So your example can be simplified to:

```yaml
id: dbtGitDockerBigQuery
namespace: dev

tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/dbt-labs/jaffle_shop
      branch: main

    - id: dbt-build
      type: io.kestra.plugin.dbt.cli.Build
      runner: DOCKER
      dbtPath: /usr/local/bin/dbt
      dockerOptions:
        image: ghcr.io/kestra-io/dbt-bigquery:latest
      inputFiles:
        .profile/profiles.yml: |
          jaffle_shop:
            outputs:
              dev:
                type: bigquery
                dataset: dwh
                fixed_retries: 1
                keyfile: sa.json
                location: EU
                method: service-account
                priority: interactive
                project: geller
                threads: 8
                timeout_seconds: 300
            target: dev
        sa.json: "{{ secret('GCP_CREDS') }}"
```

If you can give me an example with a `package.yaml` file I can check if it works as expected.
We may also miss a way to set the package.yaml file from the task.

**Comment by anna-geller** [comment]
it's in blueprints: http://localhost:8080/ui/blueprints/106

copy:

```yaml
id: dbtCLI
namespace: blueprint

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/dbt-demo
        branch: main

      - id: profile
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          packages.yml: |
            packages:
              - package: brooklyn-data/dbt_artifacts
                version: 2.4.2          
          profiles.yml: |
            jaffle_shop:
              outputs:
                dev:
                  type: bigquery
                  dataset: dwh
                  fixed_retries: 1
                  keyfile: sa.json
                  location: EU
                  method: service-account
                  priority: interactive
                  project: yourGcpProject
                  threads: 8
                  timeout_seconds: 300
              target: dev
          sa.json: "{{ secret('GCP_CREDS') }}"

      - id: dbt
        type: io.kestra.plugin.scripts.shell.Commands
        docker:
          image: ghcr.io/kestra-io/dbt-bigquery:latest
        commands:
          - dbt deps --profiles-dir .
          - dbt build --profiles-dir .
```

thx for looking into it!
