### ISSUE TITLE
Add dbt models and tests to the Execution Topology view (the same as currently shown in the Gantt view)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dbt#38]
### Issue description

dbt models and tests are difficult to read and inspect in the Gantt view:
![image](https://github.com/kestra-io/plugin-dbt/assets/86264395/396410da-fe3c-47dc-87be-845a18bb601f)

We would like to see those in the Execution Topology view:
![image](https://github.com/kestra-io/plugin-dbt/assets/86264395/b7369ced-f08f-467f-b4fd-b5b3e086d93f)

Simple reproducer to inspect/iterate on the design (you can run it directly with no setup):

```yaml
id: dbtGitDockerDuckDB
namespace: dev

tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/dbt-demo
        branch: main

      - id: dbt-build
        type: io.kestra.plugin.dbt.cli.Build
        debug: true
        dockerOptions:
          image: ghcr.io/kestra-io/dbt-duckdb:latest
        runner: DOCKER
        dbtPath: /usr/local/bin/dbt
        inputFiles:
          .profile/profiles.yml: |
            jaffle_shop:
              outputs:
                dev:
                  type: duckdb
                  path: ':memory:'
                  extensions:
                    - parquet
              target: dev
```
