### ISSUE TITLE
dbt cloud trigger run not stopping after success

### ISSUE THREAD

**Issue by aballiet** [kestra-io/plugin-dbt#41]
### Expected Behavior

When receiving success from dbt cloud API, and get the debug message `Status changed to 'Success' after 13 minutes, 22 seconds` we expect the flow to be passed in success.

### Actual Behaviour

Instead the flows says :

![image](https://github.com/kestra-io/plugin-dbt/assets/25565600/67d0530e-4ee8-4af9-91dc-9b3650d9f879)

### Steps To Reproduce

Sadly I can only offer the API response of dbt cloud for the job (who succeeded) for which the flow was indinfinitely waiting.
[response_dbt_cloud2.txt](https://github.com/kestra-io/plugin-dbt/files/12313956/response_dbt_cloud2.txt)

Probably due to the waiting of full logs coded here : https://github.com/kestra-io/plugin-dbt/blob/b265aa30b46bed0718a289728d6ee3886b53df8e/src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java#L244-L258

### Environment Information

- Kestra Version: 0.11.0-SNAPSHOT
- Plugin version: 
- Operating System (OS / Docker / Kubernetes): Kubernetes
- Java Version (If not docker):

### Example flow

```yaml
id: db-cloud-growth-production-daily-job
namespace: prod.dbt_cloud
description: "Run daily dbt cloud job for product, cohorts, success, sales, marketing & operations models"
tasks:
- id: trigger-run-job
  type: io.kestra.plugin.dbt.cloud.TriggerRun
  retry:
    maxAttempt: 5
    warningOnRetry: true
    type: constant
    interval: 1800.0
  accountId: kkkkk
  token: kkkk
  jobId: kkkkkk
```
