### ISSUE TITLE
Add `storeManifest` property to allow persisting `manifest.json` between executions

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dbt#45]
dbt allows rebuilding only models which have changed since the last run: 

```
dbt build --select state:modified+ --state ./ --defer --project-dir dbt
```

To know which models have been modified, the user would need to store the `manifest.json`. 

Currently, when user wants to reuse `manifest.json` from the last dbt task run, they need to manually persist that file via KV Store and some are also using external S3 bucket to do that. This is cumbersome. We should add properties allowing to store and load manifest from and to KV Store.

## Possible implementation

if the user adds this property, then Kestra would:
- store the manifest file in the KV Store after each run
- before starting a new run, optionally load the manifest file so dbt command can use it to `--defer` i.e. skip some models

```yaml
      - id: dbt_build
        type: io.kestra.plugin.dbt.cli.DbtCLI
        storeManifest:
          key: manifest.json
          namespace: "{{ flow.namespace }}" 
        loadManifest:
          key: manifest.json
          namespace: "{{ flow.namespace }}" 
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        projectDir: dbt
        commands:
          - dbt build --select state:modified+ --state ./ --defer --project-dir dbt
        env:
          DBT_DATABASE: "{{ inputs.gcp_project }}"
          DBT_SCHEMA: dwh
```

1. we persist the `manifest.json` in the KV Store as a JSON KV pair using the `storeManifest` to the desired KV pair key and namespace, by default using the same namespace as the flow
2. we load the `manifest.json` from the KV Store to the dbt's working directory before starting the dbt task run using the KV specified in `loadManifest`

Note: 2 properties, one for storing and one for loading manifest are needed to make it possible to load manifest generated by dbt run in a prod namespace in a dbt task running in a dev namespace - more info https://docs.getdbt.com/reference/node-selection/defer. We can use a sensible default here so that we both store and load the manifest by default.

TBD in case it's easier to implement using a FILE type input in KV, we may need to address this issue first https://github.com/kestra-io/kestra-ee/issues/1729

## Use case
This will allow users to run `dbt build --select state:modified+ --state ./ --defer` without having to manually store and load the manifest file from external sources.
