### ISSUE TITLE
Make DbtCLI task fail if any of the listed `commands` returns a non-zero error code

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dbt#78]
### Feature description

Atm, it seems that the last command is what determines success or failure. We should change that to fail the task if any command fails.

![image](https://github.com/kestra-io/plugin-dbt/assets/86264395/d49c782c-d50e-42be-8218-5caa63940c59)

![image](https://github.com/kestra-io/plugin-dbt/assets/86264395/5ec405c7-a82c-4b1b-a14b-b8fe329fd1d2)

**Comment by aballiet** [comment]
I am willing to provide a PR for this one 👍

**Comment by loicmathieu** [comment]
This is easily reproducible with such flow:

```yaml
id: multi-failed-commands
namespace: myteam

tasks:
  - id: shell
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - notfound
      - sleep 1
```

If you launch it, it ends in warning, if you remove the last command it ends in ERROR.

@aballiet are you still willing to have a look or should I take it over? The issue is not on the DBT plugin but on our script infrastructure in the [plugin-script](https://github.com/kestra-io/plugin-scripts/tree/master/plugin-script) library.

**Comment by aballiet** [comment]
You can take it @loicmathieu ,will not have time for it 😅

**Comment by fhussonnois** [comment]
@loicmathieu @aballiet I don't think the current behavior is a bug because it's actually how the `/bin/bash` interpreter works.

Using the Loic'example, we can get the expected behavior like this:

```
id: multi-failed-commands
namespace: myteam

tasks:
  - id: shell
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - set -e #Enables the immediate exit mode in case of an error.
      - notfound
      - sleep 1  # will never be executed
```

Currently, all the commands are executed in a single process so its logical that the exit_code corresponds to the final executed command.

**Comment by loicmathieu** [comment]
That's a good point, it works the same if using a Script and not a command, `set -e` should be added.
I'll close it then.

**Comment by aballiet** [comment]
> @loicmathieu @aballiet I don't think the current behavior is a bug because it's actually how the `/bin/bash` interpreter works.
> 
> Using the Loic'example, we can get the expected behavior like this:
> 
> ```yaml
> id: multi-failed-commands
> namespace: myteam
> 
> tasks:
>   - id: shell
>     type: io.kestra.plugin.scripts.shell.Commands
>     runner: PROCESS
>     commands:
>       - set -e #Enables the immediate exit mode in case of an error.
>       - notfound
>       - sleep 1  # will never be executed
> ```
> 
> Currently, all the commands are executed in a single process so its logical that the exit_code corresponds to the final executed command.

I hope I wrongly understood your point. If so, you can just ignore this comment.

Are we building Kestra for Linux nerds ?

We had an outage because of this exit code issue being very misleading, and adding `set -e` as first command is clearly not easy for anyone coming on Kestra 😅.

We now don't trust any command arrays in Kestra plugins, you could just deprecate the feature. We now loop with terraform templatefile : 

```YAML
%{ for index, command in dbt-commands ~}
      - id: dbt-commands-${ index }
        type: io.kestra.plugin.dbt.cli.DbtCLI
        retry:
          maxAttempt: ${dbt-max-attempt}
          type: constant
          interval: PT5M
          warningOnRetry: true
        docker:
          image: MY_IMAGE
          memory:
            memory: 512MB
          credentials:
            registry: "us-central1-docker.pkg.dev"
            username: "oauth2accesstoken"
            password: "{{outputs.fetchAuthToken.accessToken.tokenValue}}"
        commands:
            - ${ command }
%{ endfor ~}
```

Again, hope I wrongly understood what you said...
